package com.sandy.jnmaker.ui.notedialogs.rawnotes;

import com.sandy.jnmaker.ui.notedialogs.AbstractNotePanel ;

public abstract class RawNotesPanelUI extends AbstractNotePanel {

    private static final long serialVersionUID = 1L;

    public RawNotesPanelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.JLabel label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rawNotesTF = new javax.swing.JTextArea();

        setBackground(java.awt.Color.lightGray);

        label.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        label.setText("Edit matching note");

        rawNotesTF.setColumns(20);
        rawNotesTF.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        rawNotesTF.setLineWrap(true);
        rawNotesTF.setRows(5);
        rawNotesTF.setTabSize(4);
        rawNotesTF.setWrapStyleWord(true);
        jScrollPane1.setViewportView(rawNotesTF);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    protected javax.swing.JTextArea rawNotesTF;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
